name: Extract Weather Reports Data

on:
  schedule:
    - cron: "20 * * * *" 

jobs: 
  download-weather-report:
    runs-on: ubuntu-latest

    steps: 
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run script
        run: |
          chmod +x script.sh
          ./script.sh
